2025-10-22 22:30:21,594 - generalLogger - INFO - test_module1.run_app_logic:7 - Testing 1.1
2025-10-22 22:30:21,594 - generalLogger - INFO - test_module1.run_app_logic:8 - Testing 1.2
2025-10-22 22:30:21,594 - generalLogger - ERROR - test_module1.run_app_logic:12 - Division failed
Traceback (most recent call last):
  File "C:\Users\bjones2\Downloads\LogTest\code\test_module1.py", line 10, in run_app_logic
    1 / 0
    ~~^~~
ZeroDivisionError: division by zero
2025-10-22 22:30:47,717 - generalLogger - INFO - test_module1.run_app_logic:7 - Testing 1.1
2025-10-22 22:30:47,718 - generalLogger - INFO - test_module1.run_app_logic:8 - Testing 1.2
2025-10-22 22:30:47,718 - generalLogger - ERROR - test_module1.run_app_logic:12 - Division failed
Traceback (most recent call last):
  File "C:\Users\bjones2\Downloads\LogTest\code\test_module1.py", line 10, in run_app_logic
    1 / 0
    ~~^~~
ZeroDivisionError: division by zero
2025-10-23 13:20:34,535 - generalLogger - INFO - test_module1.run_app_logic:7 - Testing 1.1
2025-10-23 13:20:34,535 - generalLogger - INFO - test_module1.run_app_logic:8 - Testing 1.2
2025-10-23 13:20:34,535 - generalLogger - ERROR - test_module1.run_app_logic:12 - Division failed
Traceback (most recent call last):
  File "c:\Users\bjones2\TeamWhite\prototype\LogTest\code\test_module1.py", line 10, in run_app_logic
    1 / 0
    ~~^~~
ZeroDivisionError: division by zero
2025-10-23 13:27:33,519 - generalLogger - INFO - test_module1.run_app_logic:7 - Testing 1.1
2025-10-23 13:27:33,519 - generalLogger - INFO - test_module1.run_app_logic:8 - Testing 1.2
2025-10-23 13:27:33,519 - generalLogger - ERROR - test_module1.run_app_logic:12 - Division failed
Traceback (most recent call last):
  File "c:\Users\bjones2\TeamWhite\prototype\LogTest\code\test_module1.py", line 10, in run_app_logic
    1 / 0
    ~~^~~
ZeroDivisionError: division by zero
